name: sthep
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  page_transition: ^2.0.5
  get: ^4.6.1
  provider: ^6.0.2
  firebase_core: ^1.17.0
  google_sign_in: ^5.3.1
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/

  fonts:
    - family: Nemojin010
      fonts:
        - asset: assets/fonts/Nemojin010.ttf
    - family: Nemojin020
      fonts:
        - asset: assets/fonts/Nemojin020.ttf
    - family: Nemojin030
      fonts:
        - asset: assets/fonts/Nemojin030.ttf
    - family: Nemojin040
      fonts:
        - asset: assets/fonts/Nemojin040.ttf
    - family: Nemojin050
      fonts:
        - asset: assets/fonts/Nemojin050.ttf